/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
    "./app/**/*.{js,jsx}",
    "./src/**/*.{js,jsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "telephone": "390px",
        "phone": "640px",
        "tablet": "768px",
        "laptop": "1024px",
        "desktop": "1280px",
        "2xl": "1536px",
      },
    },
    extend: {
      colors: {
        "custom-black": "#000505",
        "turquoise-dark": "#021B1B",
        "sky-bleu": "#0879AA",
        "sky-marine": "#033144",
        "turquoise-claire": "#078181",
        "green-bleu": "#078888",
        "green-darker": "#055656",
        "white-claire": "#E0FFFF",
        "cyan-claire": "#86FFFF",
        "cyan-blanc": "#84FFFF",
        "turquoise-darker": "#0ABCBC",
        "red-onepiece": "rgba(235,0,27,0.5)",
        "amber-marron": "#14540A",
        "pink-boruto": "#E141B5",
        "neutral-boruto": "#383B38",
        "green-burn": "#377B28",
        "red-onepiece": "rgba(235,0,27,0.5)",
        "orange-naruto": "rgba(255,135,0,0.6)",
        "orange-db": "rgba(255,124,0,0.5)",
        "black-bleach": "rgba(0,0,0,0.8)",
        "green-hunter": "rgba(29,129,13,0.7)",
        "amber-snk": "rgba(134,85,26,0.7)",
        "neutral-mha": "rgba(212,212,212,0.8)",
        "black-jjk": "rgba(12,14,52,0.8)",
        "neutral-fma": "rgba(161,158,153,0.6)",
        "yellow-ft": "rgba(255,166,0,0.6)",
        "black-clover": "rgba(39,39,39,0.7)",
        "blue-lock": "rgba(10,30,120,0.9)",
        "slate-boruto": "rgba(56,59,56,0.8)",
        "lime-burn": "rgba(55,123,40,0.6)",
        "orange-chainsaw":"rgba(255,139,0,0.7)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};